apiVersion: v1
kind: Secret
metadata:
  name: myproductionapp-secret
  namespace: myproductionapp
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "REPLACE_ME"
  SECRET_KEY: "REPLACE_ME_LONG_RANDOM"
  DATABASE_URL: "REPLACE_ME"
